---
version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      -  JENKINS_ENV=local
    volumes:
      - "$HOME/jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME:/home"

