---
# Define the version of the compose file we're using
version: '0.1'

# Define our services
services:
  # Jenkins configuration
  master:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME:/home"

