---
# Define the version of the compose file we're using
version: '0.1'

# Define our services
services:
  # Jenkins configuration
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=admin
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME:/home"

