pipeline {
    agent {
        docker.withRegistry ('http://docker.artifacts.notjet.net') {
            image 'node:6-alpine' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Test Step"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploy Step"'
            }
        }
    }
}

